name          'confluent-schema_registry'
version       '0.1.1'
source        'https://github.com/miguno/puppet-schema_registry.git'
author        'Michael G. Noll'
license       'Apache License, Version 2.0'
summary       'Module for managing and configuring Confluent schema registry'
description   'Module for managing and configuring Confluent schema registry'
project_page  'https://github.com/miguno/puppet-schema_registry'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-supervisor'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency    'puppetlabs/stdlib', '>= 4.1.0'
